name: flutter_inappwebview_android_kontext
description: Kontext fork of the Android implementation of the flutter_inappwebview plugin.
version: 1.1.3+1.kontext.0
homepage: https://github.com/kontextso/flutter_inappwebview
repository: https://github.com/kontextso/flutter_inappwebview/tree/kontext-develop/flutter_inappwebview_android
issue_tracker: https://github.com/kontextso/flutter_inappwebview/issues
funding:
  - https://inappwebview.dev/donate/
topics:
  - html
  - webview
  - webview-flutter
  - inappwebview
  - browser

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_inappwebview_platform_interface: ^1.3.0
  flutter_inappwebview_platform_interface_kontext:
    path: ../flutter_inappwebview_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    implements: flutter_inappwebview_kontext
    platforms:
      android:
        package: so.kontext.flutter_inappwebview_android_kontext
        pluginClass: InAppWebViewFlutterPluginKontext
        dartPluginClass: AndroidInAppWebViewPlatform
